version: 2
jobs:
  build:
    working_directory: ~/ci
    machine: true
    environment:
      - secure: btt4r13t09gQlHb6gYrvGC2yGCMMHfnp1Mz1RQedc4Mpf/FfT8aE6xmK2a2i9CCvskjrP0t/BFaS4yxIURjnFRn+ugQIEa0pLspB9UJArW/vgOSpIWM9/OQ/fg8z5XuMxN6Md4DL1/iLypMNSageA1x0TRdt89+D1N1dALpg5XRCXLFbC84TLi0gjlFuib9ibPKzEhLT+anCRJ6iZMzeupDSoaCVbAtJMoDvXw4+4AcRZ1+k4MybBLyCib5boaEOt4pTT88mz4Kk0YaMwPVJyg9Qv36VqyUcPS09Yd95LuyVQ4+tZt8Y1ccbIzULsK+sLM3hLCzxlmlpN3dQBlZJiiRtQde0mgGAKyC0P0A1XjuDTywcsa5edB+fTk1Dsewz9xZ9V0NmMz8t+UNZnaSsAPga9i86jULbXUUwMVSzVRc+Xgx02liB/8qI1xYC9FM6ilStt7rn7mF0k3KbiWhcptgeXjO6Lah9FjEKd5w4MXsdUSTi/86rQaLo+kj+XdaTrXCTulKHyRyQEUj+8V1w0oVz7pcGjePHd7y5oU9ByifVQy6sytuFBfRZvugM5bKHo+i0pcWvixrZS42DrzwxZJsspANOvqSe5ifVbvOkfUppQdCBIwptxV5N1b49XPKU3W/w34QJ8xGmKp3TFA7WwVCztriFHjPgiRpB3EG99Bg=
      - REPO: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - VERSION: $CIRCLE_TAG
      - CODENAME: morbier
      - DOCKER_VERSION: 1.12.6
    steps:
      - checkout
      - run:
          name: Install Docker ${DOCKER_VERSION}
          command: |
            sudo -E apt-get -yq update
            sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install docker-engine=${DOCKER_VERSION}*
            docker version
      - run:
          name: Install python dependencies
          command: |
            pip install --user -r requirements.txt
      - run:
          name: Pull docker images
          command: make pull-images
      - run:
          name: Make Validation
          command: make validate
      - run:
          name: Run unit tests
          command: make test-unit
      - run:
          name: Run integration tests
          command: |
               n=0
               until [ $n -ge 3 ]
               do
                make test-integration && break
                n=$[$n+1]
                sleep 2
               done
      - run:
          name: Show docker ps output on fail
          command: docker ps
          when: on_fail
      - deploy:
          name: Make Crossbinary
          command: make crossbinary
      - deploy:
          name: Make Image
          command: make image
      - deploy:
          name: MAKE Tar
          command: tar cfz dist/traefik-${VERSION}.src.tar.gz --exclude-vcs --exclude dist .
## fixme: mkdocs seeems not in $PATH
#      - deploy:
#          name: Make Docs
#          command: mkdocs build --clean
